# Generated by Django 4.0.4 on 2022-05-29 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HumanResources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('department', models.CharField(choices=[('Operations', 'Operations'), ('Business', 'Business'), ('IT', 'IT'), ('Legal', 'Legal'), ('Human resources', 'Human resources')], default='Operations', max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('end_date', models.DateTimeField()),
                ('salary', models.IntegerField()),
                ('contract_duration', models.CharField(max_length=10)),
                ('contract_document', models.FileField(upload_to='contracts')),
            ],
        ),
    ]
