# Generated by Django 4.0.4 on 2022-05-29 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='humanresources',
            options={'managed': True, 'verbose_name': 'Human Resource'},
        ),
    ]
