# Generated by Django 4.0.4 on 2022-06-04 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('party', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonDisclosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(max_length=500)),
                ('date_signed', models.DateTimeField()),
                ('agreement', models.FileField(max_length=255, upload_to='')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='party.party')),
            ],
            options={
                'verbose_name': 'Non Disclosure',
            },
        ),
    ]
