# Generated by Django 4.0.4 on 2022-06-04 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0001_initial'),
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contract_area', models.CharField(choices=[('Operations', 'Operations'), ('Business', 'Business'), ('IT', 'IT'), ('Legal', 'Legal'), ('Human resources', 'Human resources'), ('Professional Service', 'Professional service')], default='Operation', max_length=50)),
                ('contract_description', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('date_signed', models.DateTimeField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('agreement', models.FileField(max_length=50, upload_to='')),
                ('price', models.CharField(max_length=50)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='party.party')),
            ],
            options={
                'verbose_name': 'Contract',
                'verbose_name_plural': 'Contract',
            },
        ),
        migrations.CreateModel(
            name='Addendum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_signed', models.DateTimeField()),
                ('effective_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('price', models.CharField(max_length=50)),
                ('agreement', models.FileField(max_length=50, upload_to='')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.contract')),
            ],
            options={
                'verbose_name': 'Addendum',
                'verbose_name_plural': 'Addenda',
            },
        ),
    ]
