# Generated by Django 4.0.4 on 2022-06-04 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_contract_addendum'),
    ]

    operations = [
        migrations.AddField(
            model_name='addendum',
            name='description',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
