# Generated by Django 4.0.4 on 2022-06-09 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0003_addendum_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Appointee',
                'verbose_name_plural': 'Appointees',
            },
        ),
        migrations.CreateModel(
            name='BoardResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField(blank=True, null=True)),
                ('resolution', models.FileField(max_length=255, upload_to='')),
                ('appointees', models.ManyToManyField(to='contract.appointee')),
            ],
        ),
    ]
