# Generated by Django 4.0.4 on 2022-05-29 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Licence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('issuing_institution', models.CharField(max_length=255)),
                ('date_issued', models.DateTimeField(blank=True)),
                ('expiry_date', models.DateTimeField(blank=True)),
                ('leseni', models.FileField(upload_to='licenses')),
            ],
            options={
                'verbose_name_plural': 'Licences',
                'managed': True,
            },
        ),
    ]
